# Generated by Django 2.2.2 on 2020-01-06 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fresher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('SecondName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField()),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('Company_Description', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Roles_and_Responsabulity', models.CharField(max_length=100)),
                ('Iterview_Date', models.DateField()),
                ('Interview_Location', models.CharField(max_length=100)),
                ('First_HrName', models.CharField(max_length=100)),
                ('Second_HrName', models.CharField(max_length=100)),
                ('First_HrNumber', models.IntegerField()),
                ('Second_HrNumber', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FresherQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Highest_Qualification', models.CharField(choices=[('Doctorate/PhD', 'Doctorate/PhD'), ('Masters/Post-Graduation', 'Masters/Post-Graduation'), ('Graduation/Diploma', 'Graduation/Diploma'), ('12th', '12th'), ('12th', '10th'), ('below 10th', 'Below 10th')], max_length=1)),
                ('Course', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Course_Type', models.CharField(max_length=100)),
                ('Passing_Year', models.CharField(max_length=100)),
                ('Resume', models.FileField(upload_to='')),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobkarleapp.Fresher')),
            ],
        ),
        migrations.CreateModel(
            name='FresherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('male', 'Male.'), ('female', 'Female.'), ('other', 'Other')], max_length=1)),
                ('Nationality', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('fresher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobkarleapp.Fresher')),
            ],
        ),
    ]
