# Generated by Django 2.2.2 on 2020-01-09 11:59

from django.db import migrations, models
import django.db.models.deletion
import jobkarleapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobkarleapp', '0004_auto_20200108_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='fresherqualification',
            name='Course',
            field=models.CharField(max_length=100, null=True, verbose_name=jobkarleapp.models.Qualification_Course),
        ),
        migrations.AlterField(
            model_name='fresherqualification',
            name='Highest_Qualification',
            field=models.CharField(max_length=100, null=True, verbose_name=jobkarleapp.models.Qualification),
        ),
        migrations.CreateModel(
            name='Qualification_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobkarleapp.Qualification')),
            ],
        ),
    ]
